### ISSUE TITLE
IRI not found

### ISSUE THREAD

**Issue by fgayanilo** [mmisw/orr-portal#115]
I get a couple of IRI not found errors but actually, the IRI does exist e.g. http://mmisw.org/ont/cf/parameter/sea_surface_wind_wave_significant_height the link to http://mmisw.org/ont/?iri=http://vocab.nerc.ac.uk/collection/P07/current/CFSN0390 is not found but a direct link leads you to the page.

If the registration of the URL is causing this problem, we may want to use a different symbol for referencing external IRIs.

**Comment by carueda** [comment]
Hey Nonong, thanks for reporting!

No, it's not a registration problem; it is a display issue.

What happens is:

- that IRI is the value of a property of a registered term
- such value itself is not registered
- in general, the UI shows a value resembling a URL with two links: one (with the `iri` parameter) in case it can be resolved against the repository itself; and the other as simply a direct link (the arrow icon). A check for existence in the repository has not been incorporated in this dispatch mainly for performance reasons. But yes, this needs improvement.

![image](https://user-images.githubusercontent.com/556505/32571380-0fb50f20-c47c-11e7-81b2-fbf7f629a8d2.png)

**Comment by fgayanilo** [comment]
Thanks for the clarification

**Comment by carueda** [comment]
Hi @fgayanilo - I realize that for **terms**,  a missing feature is to do the `http<->https` replacement for purposes of re-attempting the resolution as it was implemented for **ontologies** a long while ago: https://github.com/mmisw/orr-ont/issues/31

So, what happens here is that 

http://mmisw.org/ont/cf/parameter/sea_surface_wind_wave_significant_height 

(which is a valid term IRI as you indicate(*)) gets redirected to 

https://mmisw.org/ont/cf/parameter/sea_surface_wind_wave_significant_height 

as part of the usual apache settings on the server for security purposes.  When the request finally gets to the ORR it's then failing as not found because of the different IRI.  Again, the solution is to attempt a `https->http` replacement to re-attempt the resolution against the triple store.

![image](https://user-images.githubusercontent.com/556505/78417378-34fac900-75e6-11ea-9238-4fcdba0540ba.png)

----
(*) 
```
$ http -pb get 'https://mmisw.org/ont/api/v0/ont?iri=http://mmisw.org/ont/cf/parameter/sea_surface_wind_wave_significant_height'
{
    "names": [
        "property",
        "value"
    ],
    "values": [
        [
            "<http://mmisw.org/ont/cf/parameter/canonical_units>",
            "\"m\""
        ],
        [
            "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>",
            "<http://mmisw.org/ont/cf/parameter/Standard_Name>"
        ],
        [
            "<http://www.w3.org/2004/02/skos/core#definition>",
            "\"Wind waves are waves on the ocean surface and are the high frequency portion of a bimodal wave frequency spectrum. Significant wave height is a statistic computed from wave measurements and corresponds to the average height of the highest one third of the waves, where the height is defined as the vertical distance from a wave trough to the following wave crest.\""
        ],
        [
            "<http://www.w3.org/2004/02/skos/core#exactMatch>",
            "<http://vocab.nerc.ac.uk/collection/P07/current/CFSN0390/>"
        ]
    ]
}
```

**Comment by carueda** [comment]
I've just implemented this https-to-http reattempt for terms in 3.9.3.

For example, this now gets resolved:

 https://mmisw.org/ont/cf/parameter/sea_surface_wind_wave_significant_height

**Comment by fgayanilo** [comment]
Thanks
