### ISSUE TITLE
Improve /ont/upload documentation

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#116]
The [/ont/upload](http://cor.esipfed.org/ontapi/#!/ontology/uploadOnt) documentation could be improved by explicitly listing the possible formats. Right now it is not obvious and the _guess parameter may not always provide adequate results.

<img width="782" alt="screen shot 2017-12-16 at 11 57 49 am" src="https://user-images.githubusercontent.com/1165719/34073844-4835f6a8-e258-11e7-9129-5a42788c9824.png">

**Comment by carueda** [comment]
Thanks for the observation.  The heading of that API page points to the general documentation but certainly a direct link in this operation to https://mmisw.org/orrdoc/ontology/new/#supported-ontology-formats can be added.

**Comment by lewismc** [comment]
ack

**Comment by carueda** [comment]
Fixed by https://github.com/mmisw/mmiorr-docs/commit/325c0581bfe3e755ab9576f9206c34459b9767fc and manual update of `/var/www/html/ontapi/swagger_cor.yaml` to reflect the change for the COR.

It now looks like this:

![image](https://user-images.githubusercontent.com/556505/34922611-18c910d4-f947-11e7-8781-43e90140a8e6.png)

with "this section" a link to  https://mmisw.org/orrdoc/ontology/new/#supported-ontology-formats

This will be further updated once https://github.com/mmisw/orr-ont/issues/63 is in place.
