### ISSUE TITLE
Update YASGUI

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#128]
[YASGUI version 2.7.29](http://doc.yasgui.org/#releases) is available and provides improved functionality, we should upgrade to improve the SPARQL results page.

**Comment by lewismc** [comment]
@veer11997 please scope this issue out and see if you can provide a fix.

**Comment by carueda** [comment]
@lewismc I'm noting misbehaviors related with SPARQL queries against COR.  It seems the underlying sparql endpoint is pointing to dbpedia instead of COR's.

First I note a completely empty response for the following query even though that there's actually triples with the given subject:

```sparql
SELECT * WHERE {
  <http://cor.esipfed.org/ont/~rduerr/ADO/> ?pred ?obj .
} 
```

Then, while trying to understand this, I tried the following query:

```sparql
select distinct ?subject ?predicate ?object
where {
 ?subject ?predicate ?object.
 filter (regex(str(?subject), "http:\\/\\/cor\\.esipfed\\.org\\/ont\\/~rduerr\\/ADO\\/[^/#]*$", "i")
   || regex(str(?object), "http:\\/\\/cor\\.esipfed\\.org\\/ont\\/~rduerr\\/ADO\\/", "i"))
}
order by ?subject
```

which triggers error:

![image](https://user-images.githubusercontent.com/556505/66171650-c076ab80-e5fd-11e9-862c-a72e47ecd895.png)

Of course we are not using Virtuoso, in fact, if I click the "try query in new browser window" it takes me to `http://dbpedia.org/sparql?query=select+distinct+....`

So, it does look like the YASGUI update to `2.7.29` from `2.3.1` is not backwards compatible.

I'll try to take a look and see how to fix this.

**Comment by lewismc** [comment]
Thanks Carlos
-- 

*Lewis*
Dr. Lewis J. McGibbney Ph.D, B.Sc
*Skype*: lewis.john.mcgibbney

**Comment by lewismc** [comment]
Hi @carueda has this fix been pushed to cor.esipfed.org? Thanks

**Comment by carueda** [comment]
@lewismc yes, as part of 3.8.9.

**Comment by lewismc** [comment]
Verified on my end. This is excellent. We now have autocompletion in the SPARQL GUI... a really nice feature for anyone wanting to use it.
