### ISSUE TITLE
CSV import for vocabulary table

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-portal#31]

**Comment by carueda** [comment]
**New option in vocabulary drop-down menu:**

![orr-portal_31a](https://cloud.githubusercontent.com/assets/556505/16276262/7977fee2-3862-11e6-82c0-bf6039f48010.png)

**Dialog to enter/paste CSV contents:**

![orr-portal_31b](https://cloud.githubusercontent.com/assets/556505/16276264/797878a4-3862-11e6-9940-061ba16b6c1a.png)

**Using the Example button:**

![orr-portal_31c](https://cloud.githubusercontent.com/assets/556505/16276265/797c1180-3862-11e6-82e0-bf38242752d5.png)

**Resulting table upon importing the CSV contents:**

![orr-portal_31d](https://cloud.githubusercontent.com/assets/556505/16276263/7978789a-3862-11e6-87f2-39f74f9d69c8.png)

As illustrated with the example,  the following cases are considered for creation of the properties according to each header string in the CSV contents:

- if the string is a prefixed notation for one of the "standard" properties (eg, `skos:definition`),  then the corresponding URI is associated to the property;
- otherwise, if the string contains a colon (`:`), then it's assumed to be a full URI;
- else, the string is taken as a "local" name for the property.

**Comment by graybeal** [comment]
This is all VERY cool!

Some questions/notes:
* The 4 entries to move vocabulary or insert vocabulary I think aren't using the best word, I can't understand what they are doing or why you'd want to do that.
* What is the vocabulary referred to in "delete this vocabulary"? everything in the table? I think "delete contents of table" is more clear
* Do you want to use the term XSV throughout, since CSV really means comma-separated? I could go either way on that.
* The instructions "Except for the very first one (which should always be blank)" should more precisely say "except for the first cell in the first row ...". 
* Most CSVs will have an entry in the first cell, so maybe the code could ignore it ("which will be ignored" in the instructions). That entry often could be a clue as to what the name of the ontology would be (i.e., it could essentially be the class name for the terms). But no good way to use that knowledge, really.
* The space formatting in the example is interesting. I wanted to change it but I think with your pop-up tip it's OK.
* For URI headers, think about whether you'd like the top label to read the preferred label of the class (e.g., "Definition" for skos:definition, I assume), with the URI abbreviation in parens after. Is a nudge toward usability, but I can see either way.

**Comment by carueda** [comment]
Thanks John.

The new vocabulary tool supports multiple **classes of terms** in the same ontology (each **class of terms** being a table of terms considered as instances of a particular given class).

In general, this drop-down menu still needs to be smarter so it shows what makes sense according to the current number of "vocabularies" (again, **classes** of terms) as well as position of the particular vocabulary where the drop-down is located

I know, the term "vocabulary" is overloaded here so it will likely cause confusion, any suggestions for an alternative name when referring to the mentioned particular **class of terms**?

>The 4 entries to move vocabulary or insert vocabulary I think aren't using the best word, I can't understand what they are doing or why you'd want to do that.

The move ones should be hidden (or disabled) as there's only one vocabulary (**class** of terms) in this example.

Thanks for the wording suggestions!

**Comment by graybeal** [comment]
Oh, I see how it works. 

I think that interface, while beautiful, may be 'in the way' of a number of scenarios:
- Search the ontology for a term using the browser's search -- not everything in one page, can't see sub-sets
- Revew/read the entire contents of the ontology from top to bottom, maybe compare things across sub-sets. Have to click multiple times (would have to for scrolling as well, I suppose), and mix scrolling and clicking (e.g., to get from bottom of voc.1 to middle of voc 2 to top of voc 3 -- not so fast).
- Printing whole document

It's attractive enough, and the lost functionality minor enough, I'll be OK with it either way. Just keep in mind that if people think of their vocabularies primarily as being parts of different classes, they are likely to create separate ontologies for each class. So when many sub-vocabularies are in one ontology, it is probably an indication that the ontology is the dominant organizational paradigm, and the hierarchy is less significant, at least for many users.

A class of terms could be a term list, term set, term group, or term collection; value set (term of art in these parts); sub-vocabulary; or substitute 'concept' for term ... that's all for now. Not sure which fits best. 'class of terms' isn't really right. If you really want to be generic, call it a 'concept collection', as all terms are concepts but not all concepts are terms. Presumably this would work if the sub-terms were actually sub-classes?

**Comment by carueda** [comment]
I don't quite follow all of what you are saying ... we can probably better talk about all of this later..

For now, I was mainly "motivated" by https://github.com/mmisw/mmiorr/issues/114

**Comment by carueda** [comment]
Just pushed a change to use "term set" instead of "vocabulary" when referring to a particular term table within the vocabulary ontology.  This at least should help with the distinction.

![image](https://cloud.githubusercontent.com/assets/556505/16281586/e854606e-3879-11e6-87a0-f3cbaa4b08d5.png)

**Comment by graybeal** [comment]
I think that’s perfect, go with it and let’s see how the fans respond!

On Jun 22, 2016, at 1:07 PM, Carlos Rueda <notifications@github.com<mailto:notifications@github.com>> wrote:


Just pushed a change to use "term set" instead of "vocabulary" when referring to a particular term table within the vocabulary ontology. This at least should help with the distinction.

[image]<https://cloud.githubusercontent.com/assets/556505/16281586/e854606e-3879-11e6-87a0-f3cbaa4b08d5.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/mmisw/orr-portal/issues/31#issuecomment-227861054>, or mute the thread<https://github.com/notifications/unsubscribe/ABNU0OLka4odnrsA4EeOjQhLcC6ildzXks5qOZXtgaJpZM4I7OFe>.

========================
John Graybeal
Technical Program Manager
Center for Expanded Data Annotation and Retrieval /+/ NCBO BioPortal
Stanford Center for Biomedical Informatics Research
650-736-1632
skype: graybealski
